# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 50
    commit-message:
      prefix: "Node - "
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Github Actions - "
    directory: ./.github/workflows/
    schedule:
      interval: "monthly"