name: Build React App and Deploy to Azure Storage

on:
  push:
    branches:
      - main 
    paths:
      - 'Frontend/**'
      - 'Backend/**'
      - 'Infrastructure/**'
      - '.github/workflows/**'

  workflow_dispatch:
    inputs:
      startTimestamp:
        description: 'Start Timestamp (unix)'
        required: false
        type: number

permissions:
  packages: read
  contents: write
  id-token: write

concurrency:
  group: build-and-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '>=20'
        cache: 'npm'
        cache-dependency-path: "${{ github.workspace }}/"
    - name: Setup .NET environment
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: | 
          9.0.x
    - name: Install dependencies
      run: make setup
    - name: Build App
      env:
        FUNCTION_URL: https://${{ secrets.CUSTOM_API_DOMAIN }}/api
      run: make release
    - name: Upload site artifacts
      uses: actions/upload-artifact@main
      with:
        name: site-artifact
        path: Frontend/dist
    - name: Upload contact function artifacts
      uses: actions/upload-artifact@main
      with:
        name: function-artifact
        path: publish/out
    - name: Upload GitGub Pages artifact
      uses: actions/upload-pages-artifact@main
      with:
        path: Frontend/dist
      
  deployGithubPages:
    if: ${{ success() || needs.Build.result == 'success' }}
    uses: dylanlangston/langston-wedding.com/.github/workflows/deploy_github_pages.yml@main
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write

  deployAzureStorage:
    if: ${{ success() || needs.Build.result == 'success' }}
    uses: dylanlangston/langston-wedding.com/.github/workflows/deploy_azure.yml@main
    needs: build
    secrets: inherit
    permissions:
      packages: read
      contents: write
      id-token: write