name: Build React App and Deploy to Azure Storage

on:
  push:
    branches:
      - main 
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package-lock.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.ts'

  workflow_dispatch:
    inputs:
      startTimestamp:
        description: 'Start Timestamp (unix)'
        required: false
        type: number

concurrency:
  group: build-and-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '>=20'
        cache: 'npm'
        cache-dependency-path: "${{ github.workspace }}/"
    - name: Install dependencies
      run: npm ci 
    - name: Build React App
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@main
      with:
        name: build-artifact
        path: dist
    - name: Setup GitGub Pages
      uses: actions/configure-pages@main
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@main
        with:
          name: build-artifact
          path: dist
      - name: Deploy to Azure Storage
        uses: azure/cli@master
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch -d '$web' -s dist --overwrite -o none --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
