name: Build React App and Deploy to Azure Storage

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '>=20'
        cache: 'npm'
        cache-dependency-path: "${{ github.workspace }}/"
    - name: Install dependencies
      run: npm ci 
    - name: Build React App
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@main
      with:
        name: build-artifact
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@main
        with:
          name: build-artifact
          path: dist
      - name: Deploy to Azure Storage
        uses: azure/storage-blob-upload@main
        with: 
          source_dir: ./dist 
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} 