name: Deploy Bicep to Azure

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    name: "Deploy Bicep 💪"
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az stack group create \
              --name langston-wedding.com \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --template-file ./Infrastructure/main.bicep \
              --action-on-unmanage deleteResources \
              --deny-settings-mode None

      - name: Wait for Deployment to Finish and Get Outputs
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            outputs=$(az stack group show \
              --name langston-wedding.com \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --query "outputs" -o json)

            staticWebsiteUrl=$(echo $outputs | jq -r '.staticWebsiteUrl.value')
            functionAppUrl=$(echo $outputs | jq -r '.functionAppUrl.value')

            echo "Static Website URL: $staticWebsiteUrl"
            echo "Function App URL: $functionAppUrl"

            echo "STATIC_WEBSITE_URL=$staticWebsiteUrl" >> $GITHUB_ENV
            echo "FUNCTION_APP_URL=$functionAppUrl" >> $GITHUB_ENV

  deploy-site:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@main
        with:
          name: site-artifact
          path: dist

      - name: Deploy to Azure Storage
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob service-properties update 
              --account-name ${ secrets.AZURE_STORAGE }
              --static-website
              --index-document Index.html
              --404-document 404.html

            az storage blob upload-batch \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
              --source ./dist \
              --destination '$web'

  deploy-function:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@main
        with:
          name: function-artifact
          path: function

      - name: Deploy .NET Function App
        run: |
          az functionapp deployment source config-zip \
            --name ${{ secrets.FUNCTION_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --src function.zip