name: Deploy Site to Azure Storage

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: "Deploy Azure Storage 🚀"
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@main
        with:
          name: build-artifact
          path: dist
      - name: Deploy to Azure Storage
        uses: azure/cli@master
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch -d '$web' -s dist --overwrite -o none --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"