name: Unit and Integration Testing

run-name: Testing on push by @${{ github.actor }}

on:
  push:
    branches:
      - main 
    paths:
      - 'Frontend/**'


  workflow_dispatch:
    inputs:
      startTimestamp:
        description: 'Start Timestamp (unix)'
        required: false
        type: number

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '>=20'
        cache: 'npm'
        cache-dependency-path: "${{ github.workspace }}/"
    - name: Install node dependencies
      run: npm ci --prefix ./Frontend
    - name: Build React App
      run: npm run test --prefix ./Frontend