name: Unit and Integration Testing

run-name: Testing on push by @${{ github.actor }}

on:
  push:
    branches:
      - main 
    paths:
      - 'Frontend/**'
      - 'Backend/**'

  workflow_call:

  workflow_dispatch:
    inputs:
      startTimestamp:
        description: 'Start Timestamp (unix)'
        required: false
        type: number

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    if: ${{ github.event.commits[0].author.name != 'dependabot[bot]' }}
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '>=20'
        cache: 'npm'
        cache-dependency-path: "${{ github.workspace }}/"
    - name: Setup .NET environment
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: | 
          9.0.x
    - name: Install dependencies
      run: make setup
    - name: Test App
      run: make test