name: Unit and Integration Testing

run-name: Testing on push by @${{ github.actor }}

on:
  push:
    branches:
      - main 
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package-lock.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.ts'

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '>=20'
        cache: 'npm'
        cache-dependency-path: "${{ github.workspace }}/"
    - name: Install dependencies
      run: npm ci 
    - name: Build React App
      run: npm run test